### ISSUE TITLE
docker wireguard?

### ISSUE THREAD

**Issue by clarity99** [jbencina/vpn#1]
Any chance of getting wireguard in docker as well? I've tried myself, but am getting stumped connecting the wg0 interface from within wireguard container to pihole container, so that vpn clients can access pihole.

**Comment by jbencina** [comment]
I think it's possible. I'm not a docker expert so it took me a while to get this far. I'm guessing your issue is not explicitly setting an IP address in https://github.com/jbencina/vpn/blob/master/pi-hole/docker-compose.yaml? I had issues with pihole seeing cloudflared until I configured the network internally this way.
